apiVersion: v1
kind: Service
metadata:
  name: auth-api-service
spec:
  selector:
    app: auth-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auth-api-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  defaultBackend:
    service:
      name: auth-api-service
      port: 
        number: 80
  rules:
  - host: local.auth.net
    http:
      paths:
      - path: /auth
        pathType: Prefix
        backend:
          service:
            name: auth-api-service
            port:
              number: 80
        